name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  unit-test:
    name: Unit tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
